version: "2"
services:
    activemq:
        image: rmohr/activemq:5.15.6-alpine
        ports:
            - 8161:8161
        expose:    
            - 61616
            - 5672
        volumes:
            - ./conf:/opt/apache-activemq-5.15.6/conf
    rabbitmq:
        build:
            dockerfile: Dockerfile-rmqshovel
            context: .
        ports:
            - 15672:15672
            - 5672:5672            
        expose:
            - 4369
            - 22

    control-plane:
        env_file: .env
        build:
            dockerfile: Dockerfile-controller
            context: .
        volumes:
            - ~/.aws:/var/lib/rabbitmq/.aws

    s3:
        image: localstack/localstack
        environment:
            - SERVICES=s3
        expose:
            - 4572
        ports:
            - 4572:4572
    testing:
        env_file: .env
        build:
            context: testing
        volumes:
            - ./testing:/app
            - ~/.aws:/root/.aws
        entrypoint: /app/bootstrap.sh


    publish-to-s3:
        build:
            context: publishS3
        volumes:
            - ./publishS3:/app
        entrypoint: >
            npm install && nc -l 5555 && sls invoke local -f publish-to-s3
            
