version: "2"
services:
    activemq:
        image: rmohr/activemq:5.15.6-alpine
        ports:
            - 8161:8161
        expose:    
            - 61616
            - 5672
        volumes:
            - ./conf:/opt/apache-activemq-5.15.6/conf
    rabbitmq:
        build:
            dockerfile: Dockerfile-rmqshovel
            context: .
        ports:
            - 15672:15672
            - 5672:5672            
        expose:
            - 4369
            - 22

    control-plane:
        env_file: .env
        build:
            dockerfile: Dockerfile-controller
            context: .

    testing:
        env_file: .env
        build:
            context: testing
        volumes:
            - ./testing:/app
        entrypoint: /app/bootstrap.sh

